version: '3'

services:
  app:
    image: events
    build: .
    volumes:
      - ./:/dist/
    ports:
      - 3000:3000
    command: node .
    environment:
      PORT: 3000
      REDIS_URL: redis:6379
      LOCK_EXPIRY_MS: 1000
      HOLD_EXPIRY_MS: 60000
      MAX_EVENT_SEATS_PER_USER: 3
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379